---
- hosts: 172.31.12.137
  become: yes
  tasks:
    - name: i want to install git on redhat
      yum:
        name: git
        state: present
    - name: i want to install webserver on redhat
      yum:
        name: http
        state: present
    - name: i want to start my webserver
      service:
        name: http
        state: started